### ISSUE TITLE
Use a python module to get the translation

### ISSUE THREAD

**Issue by mrose17** [starsnotinjars/Automatic-Website-Categorizers#4]
the Description process involves a manual step to cut-and-paste to get a translation, followed by a cut-and-paste going back. there has to be a python module that can invoke google translate so we can keep this entirely automated.

**Comment by starsnotinjars** [comment]
Hi Marshall, there is a Python module that can invoke Google Translate, it is a Google Translate API. You can read up about it here: https://www.programmableweb.com/news/google-translate-api-back...-fee/2011/08/29. It is not free, which is why I did not use it when I created the first version of the program. I'm not sure logistically what would be the best way to go about paying for the API. Maybe Brave could provide me with a work credit card? Let me know what you think.

**Comment by bsclifton** [comment]
Looks like we have a few options here:
- https://github.com/wilfilho/BingTranslator
- https://github.com/openlabs/Microsoft-Translator-Python-API/

I'll try to throw a code example together tonite and see how it goes 😄

**Comment by bsclifton** [comment]
Example shared in https://github.com/starsnotinjars/Automatic-Website-Categorizers/pull/8

**Comment by starsnotinjars** [comment]
Thank you! I'll take a look at it soon.

**Comment by mrose17** [comment]
@starsnotinjars - before we go to a paid srevice, let's try either of the two examples that brian put together

**Comment by starsnotinjars** [comment]
Agreed!

**Comment by starsnotinjars** [comment]
Bad news about Microsoft Translator: "DataMarket and Data Services are being retired and will stop accepting new orders after 12/31/2016. Existing subscriptions will be retired and cancelled starting 3/31/2017. Please reach out to your service provider for options if you want to continue service."

**Comment by starsnotinjars** [comment]
@mrose17 , @bsclifton Both translators (Microsoft and Bing) rely on the Microsoft Translator API, which can no longer be downloaded because it is retiring.

**Comment by bsclifton** [comment]
😭

**Comment by starsnotinjars** [comment]
I'm looking into the Yandex API right now, that might serve our needs.

**Comment by starsnotinjars** [comment]
It looks like Yandex API will be useful. I'm working on integrating it into current code.

**Comment by mrose17** [comment]
great! is there a python module for it?

**Comment by starsnotinjars** [comment]
Yes! https://github.com/dveselov/python-yandex-translate

**Comment by mrose17** [comment]
groovy!

**Comment by starsnotinjars** [comment]
Done with Yandex!
