### ISSUE TITLE
a concise definition?

### ISSUE THREAD

**Issue by mrose17** [starsnotinjars/Automatic-Website-Categorizers#5]
is this a fair synopsis:

the title search retrieves the

    <html><head><title>...</title>

element value, the description search retrieves the

    <html><head><meta name="description" content="....">

attribute value. and both then look for keywords in order to come up with categories.

**Comment by starsnotinjars** [comment]
Hi Marshall, the title search program relies on the program GoogleScraper to extract the the title of the first website that pops up from a Bing search. If you go to the GoogleScraper github site and then to the parsing.py file (https://github.com/NikolaiT/GoogleScraper/blob/master/GoogleScraper/parsing.py), you can go down to line 563 to see where he defines the Bing parser class. Within this class he wrote code to search for the titles of the websites that are found:

    normal_search_selectors = {
        'results': {
            'us_ip': {
                'container': '#b_results',
                'result_container': '.b_algo',
                'link': 'h2 > a::attr(href)',
                'snippet': '.b_caption > p::text',
                'title': 'h2::text',
'visible_link': 'cite::text'

Honestly, I haven't played around with certain aspects of python coding, but it looks like he is taking the text right after the h2 tag of html markup to find the title. 

As far as what the description searcher is doing, it is true that it is retrieving the description in the manner that you described. 

Please let me know if you have any more questions!

**Comment by mrose17** [comment]
@starsnotinjars - so for title search, it's looking for the first &lt;h2> element. is that the gist of it?

**Comment by starsnotinjars** [comment]
As far as I can tell he is taking the text right after the h2 tag of html markup to find the title. I'm not sure what you mean by element.

**Comment by mrose17** [comment]
the HTML markup for a website is often like this:

        <html>
        <head>
        <title>...</title>
        <meta name="..." content="....">
        ...
        </head>
        <body>
        <h1>...</h1>
        <p>...</p>
        <h2>...</h2>
        <p>...</p>
        ...
        </body>
        </html>

what i am trying to understand is where the title searcher is getting the text. my guess from the information above is that it's getting it from the &lt;h2>...&lt;</h2> ... but that's enough for me to understand, thanks!
